### ISSUE TITLE
Build broken

### ISSUE THREAD

**Issue by JuergenKosel** [JuergenKosel/s7commwireshark#2]
Build broken by commit 43c677058f1b15883fe4309f4b9900a56c7ea5eb
gcc gives the following output:
```
wireshark/epan/dissectors/s7commwireshark/src/s7comm_plus/packet-s7comm_plus.c: In function 's7commp_decode_value':
/home/juergen/C++Programme/wireshark/epan/dissectors/s7commwireshark/src/s7comm_plus/packet-s7comm_plus.c:5587:17: error: variable 'value_item' set but not used [-Werror=unused-but-set-variable]
     proto_item *value_item = NULL;
                 ^~~~~~~~~~
cc1: all warnings being treated as errors
```

**Comment by JuergenKosel** [comment]
Fixed by commit d84e504107d876ab1259a2f00af57ba726ac1d62
